const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const toast=(message)=>{const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),3200)};
// Menu responsivo
const menu=$('.menu-toggle'),nav=$('.nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});$$('.nav-link').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
// Navegação ativa por seção
const links=$$('.nav-link');const observedSections=$$('main section[id]');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')===`#${e.target.id}`))}}),{rootMargin:'-35% 0px -55% 0px'});observedSections.forEach(s=>observer.observe(s));
// Revelação progressiva
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');revealObserver.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%6*45,220)}ms`;revealObserver.observe(el)});
// Modal de componentes, ambientes e investigação
const modal=$('#modal'),modalTitle=$('#modal-title'),modalText=$('#modal-text');const openModal=(el)=>{modalTitle.textContent=el.dataset.modalTitle||'Detalhes';modalText.textContent=el.dataset.modalText||'';modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('.modal-close').focus()};$$('[data-modal-title]').forEach(el=>el.addEventListener('click',()=>openModal(el)));$('.modal-close').addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});modal.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('.modal')?.classList.remove('open')}});
// Feedback genérico
$$('[data-toast]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.toast)));
// Release gate checklist
const gateChecks=$$('.check-items input'),checkCount=$('#check-count'),gateResult=$('#gate-result');const updateGate=()=>{const n=gateChecks.filter(x=>x.checked).length;checkCount.textContent=`${n}/9`;if(n===9){gateResult.className='decision-state';gateResult.innerHTML='<span class="decision-icon" style="background:#124b3e;color:#41df9a">✓</span><div><small>DECISION STATE</small><h3 style="color:#41df9a">GO — liberação autorizada</h3><p>Todos os critérios foram aprovados na simulação.</p></div>'}else{gateResult.className='decision-state no-go-state';gateResult.innerHTML='<span class="decision-icon">!</span><div><small>DECISION STATE</small><h3>Aguardando critérios</h3><p>Marque todos os itens para liberar a simulação.</p></div>'}};gateChecks.forEach(c=>c.addEventListener('change',updateGate));$('#simulate-gate').addEventListener('click',()=>{const n=gateChecks.filter(x=>x.checked).length;toast(n===9?'GO — liberação autorizada.':'NO-GO — ainda existem critérios pendentes.');updateGate()});
// Cards do pipeline e simulação progressiva
const pipeInfo={Commit:'Objetivo: registrar uma mudança versionada. Entrada: código revisado. Saída: trigger do pipeline. Automático.',Build:'Objetivo: compilar e instalar dependências. Entrada: commit. Saída: build executável. Automático.',Testes:'Objetivo: verificar comportamento. Entrada: build. Saída: testes PASS/FAIL. Automático.',Análise:'Objetivo: detectar falhas e vulnerabilidades. Entrada: código. Saída: quality gate. Automático.',Artefato:'Objetivo: gerar pacote identificável. Entrada: build aprovado. Saída: artefato versionado. Automático.',Staging:'Objetivo: publicar para homologação. Entrada: artefato. Saída: ambiente validável. Automático.',Aprovação:'Objetivo: registrar governança e decisão. Entrada: evidências. Saída: autorização. Manual.',Produção:'Objetivo: disponibilizar aos usuários. Entrada: aprovação. Saída: go-live. Manual.'};$$('.pipe-step').forEach(s=>s.addEventListener('click',()=>{const key=s.dataset.pipe;const txt=pipeInfo[key];toast(txt)}));const runBtn=$('#run-pipeline'),steps=$$('.pipe-step'),log=$('#pipeline-log');let running=false;runBtn.addEventListener('click',()=>{if(running)return;running=true;steps.forEach(s=>s.classList.remove('running','complete'));runBtn.disabled=true;let i=0;const run=()=>{if(i>0)steps[i-1].classList.replace('running','complete');if(i===steps.length){log.textContent='PIPELINE COMPLETED  |  Build: SUCCESS  |  Tests: PASS  |  Security: PASS  |  Artifact: READY  |  Staging: APPROVED  |  Production: DEPLOYED';toast('Pipeline concluído com sucesso.');runBtn.disabled=false;running=false;return}const name=steps[i].dataset.pipe;steps[i].classList.add('running');log.textContent=`[${String(i+1).padStart(2,'0')}/08] ${name.toUpperCase()} — em execução...`;i++;setTimeout(run,650)};run()});
// Smoke tests e barra de progresso
const smokeChecks=$$('.smoke-grid input'),smokeProgress=$('#smoke-progress'),smokePercent=$('#smoke-percent'),smokeStatus=$('#smoke-status');const updateSmoke=()=>{const n=smokeChecks.filter(x=>x.checked).length;const pct=Math.round(n/7*100);smokeProgress.style.width=`${pct}%`;smokePercent.textContent=`${pct}%`;smokeStatus.textContent=`${n} de 7 verificações aprovadas`;if(n===7)toast('Post-deploy validation aprovada.');};smokeChecks.forEach(c=>c.addEventListener('change',updateSmoke));
// Decisão do incidente: NO-GO é a decisão correta do caso
$$('[data-decision]').forEach(btn=>btn.addEventListener('click',()=>{const out=$('#decision-feedback');if(btn.dataset.decision==='nogo'){out.textContent='DECISÃO CORRETA: NO-GO. Inconsistência detectada; preservar evidências e executar rollback conforme necessário.';out.style.color='var(--green)';toast('NO-GO registrado: produção permanece bloqueada.')}else{out.textContent='GO INCORRETO PARA ESTE CENÁRIO: a diferença de 223 pedidos impede a liberação segura.';out.style.color='var(--red)';toast('Atenção: a inconsistência impede o GO.')}}));
// Voltar ao topo
const topBtn=$('.back-top');window.addEventListener('scroll',()=>topBtn.classList.toggle('visible',scrollY>600));topBtn.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));

// V2 — detalhes de preparação, agenda, smoke tests e deployment simulation
$$('[data-prep]').forEach(card=>card.addEventListener('click',()=>toast(card.dataset.prep)));
$$('.window-grid [data-modal-title]').forEach(card=>card.addEventListener('click',()=>openModal(card)));
// Contadores entram em cena quando o dashboard fica visível.
const countObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;$$('.count-up',entry.target).forEach(el=>{const target=Number(el.dataset.target),duration=800,start=performance.now();const tick=now=>{const progress=Math.min((now-start)/duration,1);el.textContent=Math.floor(progress*target);if(progress<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)});countObserver.unobserve(entry.target)}),{threshold:.4});const metrics=$('.metrics');if(metrics)countObserver.observe(metrics);
// Smoke tests: a execução guiada mantém o painel legível e gera evidência.
const smokeButton=$('#run-smoke');if(smokeButton)smokeButton.addEventListener('click',()=>{if(smokeButton.dataset.running)return;smokeButton.dataset.running='1';smokeChecks.forEach(c=>c.checked=false);updateSmoke();let i=0;const run=()=>{if(i>=smokeChecks.length){smokeButton.textContent='Smoke tests aprovados';smokeButton.dataset.running='';return}smokeChecks[i].checked=true;smokeChecks[i].dispatchEvent(new Event('change'));i++;setTimeout(run,260)};smokeButton.textContent='Executando...';run()});
// Investigação com feedback visual sem contradizer a decisão NO-GO.
$$('.invest-card').forEach(card=>card.addEventListener('dblclick',()=>toast('Evidência adicionada à trilha de auditoria.')));
// Simulação completa da implantação — a inconsistência bloqueia a produção.
const deploymentButton=$('#start-deployment'),deploySteps=$$('.deploy-track span'),deploymentResult=$('#simulation-result');if(deploymentButton)deploymentButton.addEventListener('click',()=>{if(deploymentButton.dataset.running)return;deploymentButton.dataset.running='1';deploymentButton.textContent='Simulando...';deploySteps.forEach(s=>s.className='');let i=0;const states=['PREPARING','BACKUP','DEPLOY','MIGRATION','VALIDATION','GO/NO-GO','RESULT'];const run=()=>{if(i>0)deploySteps[i-1].classList.remove('current'),deploySteps[i-1].classList.add('done');if(i===deploySteps.length){deploySteps[5].classList.remove('done');deploySteps[5].classList.add('blocked');deploySteps[6].classList.add('blocked');deploymentResult.textContent='DEPLOYMENT BLOCKED — NO-GO: 223 pedidos ausentes na reconciliação. Rollback necessário.';deploymentResult.style.color='var(--red)';deploymentButton.textContent='Reexecutar simulação';deploymentButton.dataset.running='';toast('Simulação encerrada: produção bloqueada.');return}deploySteps[i].classList.add('current');deploymentResult.textContent=`${states[i]} — etapa em execução...`;i++;setTimeout(run,520)};run()});
// Estado de foco e aria nos cards que funcionam como controles.
$$('.env-card,.pipe-step,.invest-card,.prep-grid button,.window-grid button').forEach(el=>{if(!el.hasAttribute('aria-label'))el.setAttribute('aria-label',el.textContent.trim().replace(/\s+/g,' '))});

// CINEMATIC INTRO — boot, 404 → Nota Alta, deployment e transição data-wipe
(()=>{
  const intro=$('#intro-screen');if(!intro)return;
  const terminal=$('#intro-terminal-lines'),phase=$('#intro-phase'),progress=$('#intro-progress-bar'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const boot=['initializing system...','loading project...','loading deployment modules...','checking environment...','establishing connection...','system ready.'];let bootIndex=0,skip=false,timers=[];
  const later=(fn,ms)=>{const id=setTimeout(fn,ms);timers.push(id);return id};
  const finish=()=>{if(skip)return;skip=true;timers.forEach(clearTimeout);intro.classList.add('exiting');progress.style.width='100%';later(()=>{intro.classList.add('dismissed');document.body.classList.remove('intro-active');later(()=>intro.remove(),950)},reduced?220:900)};
  const start=()=>{
    document.body.classList.add('intro-active');
    if(reduced){boot.forEach((line)=>{const p=document.createElement('p');p.textContent=line;terminal.appendChild(p)});phase.textContent='DEPLOYMENT READY';intro.classList.add('turning','final');progress.style.width='100%';later(finish,1100);return}
    const typeLine=()=>{if(skip)return;if(bootIndex<boot.length){const p=document.createElement('p');p.textContent=boot[bootIndex++];terminal.appendChild(p);progress.style.width=`${Math.min(bootIndex/boot.length*24,24)}%`;later(typeLine,245)}};typeLine();
    later(()=>{phase.textContent='SYSTEM DETECTED';progress.style.width='31%'},1750);later(()=>{phase.textContent='PROJECT FOUND';progress.style.width='37%'},2050);later(()=>{phase.textContent='DEPLOYMENT ACTIVITY';progress.style.width='43%'},2350);
    later(()=>{phase.textContent='404 / SIGNAL';progress.style.width='51%'},2700);later(()=>{intro.classList.add('turning');phase.textContent='SIGNAL TRANSFORMING';progress.style.width='63%'},3500);later(()=>{intro.classList.add('final');phase.textContent='GROUP IDENTIFIED';progress.style.width='77%'},4300);later(()=>{phase.textContent='DEPLOYMENT READY';progress.style.width='93%'},5350);later(finish,6500);
  };
  const skipIntro=()=>{if(skip)return;skip=true;timers.forEach(clearTimeout);intro.classList.add('exiting');progress.style.width='100%';setTimeout(()=>{intro.classList.add('dismissed');document.body.classList.remove('intro-active');setTimeout(()=>intro.remove(),950)},reduced?80:500)};
  $('#skip-intro')?.addEventListener('click',skipIntro);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&intro.isConnected)skipIntro()},{once:false});
  // Partículas leves em canvas, reduzidas no mobile para preservar performance.
  const canvas=$('#intro-particles'),ctx=canvas?.getContext('2d');if(ctx){let w=0,h=0;const count=innerWidth<700?24:48,pts=Array.from({length:count},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.5+.3,v:(Math.random()-.5)*.00018}));const resize=()=>{w=canvas.width=innerWidth*devicePixelRatio;h=canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)};resize();addEventListener('resize',resize);const draw=()=>{if(!intro.isConnected)return;ctx.clearRect(0,0,innerWidth,innerHeight);pts.forEach((p,i)=>{p.y+=p.v;if(p.y>1)p.y=0;if(p.y<0)p.y=1;const x=p.x*innerWidth,y=p.y*innerHeight;ctx.fillStyle=i%4===0?'#41df9a99':'#28c9ff99';ctx.beginPath();ctx.arc(x,y,p.r,0,Math.PI*2);ctx.fill();if(i>0){const q=pts[i-1],d=Math.hypot((q.x-p.x)*innerWidth,(q.y-p.y)*innerHeight);if(d<145){ctx.strokeStyle=`rgba(40,201,255,${(1-d/145)*.16})`;ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(q.x*innerWidth,q.y*innerHeight);ctx.stroke()}}});requestAnimationFrame(draw)};if(!reduced)draw()}
  start();
})();

// AUDIO SYSTEM — controles personalizados, sem autoplay
(()=>{
  const audio=$('#music-audio'),card=$('#music-card'),play=$('#music-play'),seek=$('#music-seek'),volume=$('#music-volume'),current=$('#music-current'),duration=$('#music-duration'),status=$('#music-status');if(!audio||!card)return;
  const formatTime=seconds=>{if(!Number.isFinite(seconds))return'0:00';const m=Math.floor(seconds/60),s=Math.floor(seconds%60).toString().padStart(2,'0');return`${m}:${s}`};
  const sync=()=>{const pct=audio.duration?(audio.currentTime/audio.duration)*100:0;seek.value=pct;current.textContent=formatTime(audio.currentTime)};
  audio.volume=Number(volume.value);audio.autoplay=false;
  audio.addEventListener('loadedmetadata',()=>{duration.textContent=formatTime(audio.duration);seek.value=0});audio.addEventListener('timeupdate',sync);audio.addEventListener('play',()=>{card.classList.add('playing');play.textContent='❚❚';play.setAttribute('aria-label','Pausar Not Found');status.textContent='● PLAYING'});audio.addEventListener('pause',()=>{card.classList.remove('playing');play.textContent='▶';play.setAttribute('aria-label','Reproduzir Not Found');status.textContent='● IDLE'});audio.addEventListener('ended',()=>{audio.currentTime=0;sync();status.textContent='● COMPLETE';toast('Not Found finalizada.');});
  play.addEventListener('click',()=>{if(audio.paused){audio.play().catch(()=>toast('Clique novamente para iniciar o áudio.'))}else audio.pause()});seek.addEventListener('input',()=>{if(audio.duration)audio.currentTime=(Number(seek.value)/100)*audio.duration});volume.addEventListener('input',()=>{audio.volume=Number(volume.value)});card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect();card.style.setProperty('--mx',`${((e.clientX-r.left)/r.width)*100}%`);card.style.setProperty('--my',`${((e.clientY-r.top)/r.height)*100}%`)});card.addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();play.click()}});
})();
